import { Video } from './types';

export const videos: Video[] = [
    {
        id: '1',
        title: 'Modern Architecture - Minimalist Home Design',
        duration: '12:45',
        views: '1.2M',
        uploadedAgo: '2 days ago',
        creatorName: 'Design Lab',
        tags: ['Architecture', 'Design', 'Minimalism'],
        youtubeId: 'dQw4w9WgXcQ', // Placeholder, will replace with diverse IDs
        thumbnailUrl: 'https://img.youtube.com/vi/dQw4w9WgXcQ/hqdefault.jpg',
    },
    {
        id: '2',
        title: 'Exploring the Swiss Alps in 4K',
        duration: '22:10',
        views: '850K',
        uploadedAgo: '1 week ago',
        creatorName: 'Traveler Joe',
        tags: ['Travel', 'Nature', '4K'],
        youtubeId: '9m5g9q6-6g4',
        thumbnailUrl: 'https://img.youtube.com/vi/9m5g9q6-6g4/hqdefault.jpg',
    },
    {
        id: '3',
        title: 'The Future of AI - 2024 and Beyond',
        duration: '15:30',
        views: '2.5M',
        uploadedAgo: '3 hours ago',
        creatorName: 'Tech Insider',
        tags: ['AI', 'Tech', 'Future'],
        youtubeId: 'u6XUf0j0E24',
        thumbnailUrl: 'https://img.youtube.com/vi/u6XUf0j0E24/hqdefault.jpg',
    },
    {
        id: '4',
        title: 'Cooking the Perfect Italian Carbonara',
        duration: '08:15',
        views: '400K',
        uploadedAgo: '5 days ago',
        creatorName: 'Chef Mario',
        tags: ['Cooking', 'Food', 'Italian'],
        youtubeId: '3AAdKl1UYZs',
        thumbnailUrl: 'https://img.youtube.com/vi/3AAdKl1UYZs/hqdefault.jpg',
    },
    {
        id: '5',
        title: 'Lo-fi Hip Hop Beats to Study/Relax To',
        duration: '1:00:00',
        views: '15M',
        uploadedAgo: '1 month ago',
        creatorName: 'Lofi Girl',
        tags: ['Music', 'Lo-fi', 'Study'],
        youtubeId: 'jfKfPfyJRdk',
        thumbnailUrl: 'https://img.youtube.com/vi/jfKfPfyJRdk/hqdefault.jpg',
    },
    {
        id: '6',
        title: 'Gaming Setup Tour 2024 - Ultra Clean',
        duration: '10:20',
        views: '1.1M',
        uploadedAgo: '2 weeks ago',
        creatorName: 'Setups & More',
        tags: ['Gaming', 'Tech', 'Setup'],
        youtubeId: 'v7_YvT2g8g8',
        thumbnailUrl: 'https://img.youtube.com/vi/v7_YvT2g8g8/hqdefault.jpg',
    },
    {
        id: '7',
        title: 'Cyberpunk 2077 - Path Tracing Gameplay',
        duration: '18:50',
        views: '900K',
        uploadedAgo: '4 days ago',
        creatorName: 'Digital Foundry',
        tags: ['Gaming', 'Cyberpunk', 'RTX'],
        youtubeId: 'pS-fK7pW4-I',
        thumbnailUrl: 'https://img.youtube.com/vi/pS-fK7pW4-I/hqdefault.jpg',
    },
    {
        id: '8',
        title: 'How to Build a Custom Mechanical Keyboard',
        duration: '25:00',
        views: '600K',
        uploadedAgo: '3 weeks ago',
        creatorName: 'Keyboard Enthusiast',
        tags: ['Tech', 'DIY', 'Keyboard'],
        youtubeId: '7a_XkG9W9pE',
        thumbnailUrl: 'https://img.youtube.com/vi/7a_XkG9W9pE/hqdefault.jpg',
    },
    {
        id: '9',
        title: 'SpaceX Starship Launch Highlights',
        duration: '05:40',
        views: '4.2M',
        uploadedAgo: '1 day ago',
        creatorName: 'SpaceX',
        tags: ['Science', 'Space', 'Starship'],
        youtubeId: 'xP8C4_zLh8I',
        thumbnailUrl: 'https://img.youtube.com/vi/xP8C4_zLh8I/hqdefault.jpg',
    },
    {
        id: '10',
        title: 'Street Photography in Tokyo Night',
        duration: '14:20',
        views: '300K',
        uploadedAgo: '6 days ago',
        creatorName: 'PhotoWalk',
        tags: ['Photography', 'Tokyo', 'Night'],
        youtubeId: 'W_fGleIkxQU',
        thumbnailUrl: 'https://img.youtube.com/vi/W_fGleIkxQU/hqdefault.jpg',
    },
    {
        id: '11',
        title: 'Healthy Breakfast Ideas for Busy Mornings',
        duration: '09:30',
        views: '180K',
        uploadedAgo: '2 days ago',
        creatorName: 'Healthy Living',
        tags: ['Food', 'Health', 'Morning'],
        youtubeId: '9_5wHw6l11o',
        thumbnailUrl: 'https://img.youtube.com/vi/9_5wHw6l11o/hqdefault.jpg',
    },
    {
        id: '12',
        title: 'The Art of Cinematography',
        duration: '20:00',
        views: '550K',
        uploadedAgo: '1 month ago',
        creatorName: 'Film School',
        tags: ['Film', 'Cinematography', 'Art'],
        youtubeId: 'vIu85CBfPH0',
        thumbnailUrl: 'https://img.youtube.com/vi/vIu85CBfPH0/hqdefault.jpg',
    },
];
